language: python
branches:
  only:
  - master
install:
- pip install pelican markdown
before_script:
- pelican-themes -i ./themes/blue-penguin
script:
- make publish
after_success: "./deploy.sh"
env:
  global:
  - secure: ebuvzbMDBTB6EWTZ5ngz3+GzBJSWLTE+tEgpzw+wpIkc3G2B/0MJ2dVNfiVViynw3iHWnJjta1C4AW+afpE8JR1qnkQyjhyO6i4501gBHaKCeHshEhjySTpw7W4aKH2JHWYryY50AI0+9MIjwuhlfB4U3MEY5G391qLNKOUuwXx3wlsnsgnRZ1FBANJHFdpLWI16Hnm7EytpiJmCt74iVTe0fzpwRRn2AbH1RGNIPF8T1xB0vMx5bRXu9XIQnYu/4q4unVyrPTQOY2SNu5qvS/UajZaycw3DpCSdlcgbw2XTC6DQQDlWV23aXKG8H8HWQwHQoHvK4HXzil4+mstqZPv5EuBZIHoBH7F1qpnnGiuAJRDlakOraPVKIaE22yF+ory55SnGJuZg95vSmAMeKfwnMPd3DGND5ipCskaINrWbvCtwLcyPHwLo+e5DpdS7RJsMreN7wdyVjdQO2y+WEWk1pEkiC/IGnO/ItoU+ZwmHKGgjA9rGFJrW7iwdhw3rVZnA/hroh6TXQhat8qnXOdrrbzW5tag4ObjXLmiCmD1UNzcJmJvs2XxLIytHujXXwX+FNGAylQ52C9WsMxIsCT0ErjVHjKM2AuQERn0t7nO40gf0jMJ2kX+TyHer++9GzJJTZxR/mhsA3q1Kn6rC5qkxUMzXL/K4PPAX6pPfheg=
  - secure: JMhzeICKzoTJTbvr8HgFGWe5r8q6oQJXv7jIEq7IUUAP6UXAgD3JE6g4HuDaVSn02VOpP1bSzZb6FuEzPJ+kW6+/CC7yxlCrANOg3RFmbDGUk9hsRaTSQ7fOA3C/alFWN+CBf8qKiB80tT1UoNWwYYeMuOtoqRyKh2tyVspTH4YyAdlAdZ91CACvNjns219tTr7RCyuvSgJB4sgCeru0ecLuxrZJvV6RE+7mAen3rEVZOuCtmBM6e6+KaKBOZM2v0ZMdcPDwCpWQShD3EyJ36MAh8Jhn8pOgEKePaDqfe6YPkLpIdGZPhiM/HsTUBORCAa/J6jYY36xfphbgmmlK8Mx/+LXU4fZ3t+m/5qOr74yLkANrz6nr+U5eb/5Xd7fMsS4GtRlmVyOUZLdvk0BerMxRbijGTtoqxnfmEX1oSLO93l1HGM8fSiUK7cDA8PyVlqJVc/peKkGk2grYyzVc4qQFQgMBOnWo1UAZ2ihab59ri7Q6A8Qu6yqyzVt6mg6Yq01ETKSkj8vYxBVaGp1w2SnR62Qf4PYnOmM7rXq/iE1iNYgyaJ7nfRB/O2JWNlwfBUiEMpGcpk3aQbdEQX39s2fJ+Y++74kkSuYD18qEMMOxTyxSYPWJIMegmUFumooeXpYZXW6BE3fiyq5g5NozF7Bkwjz6IFE5rB+9F+AweE0=
